{{/* Store Front Service */}}
apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.global.environment }}
spec:
  type: {{ .Values.storeFront.service.type }}
  selector:
    app: store-front
  ports:
    - port: {{ .Values.storeFront.service.port }}
      targetPort: {{ .Values.storeFront.service.targetPort }}
      protocol: TCP
      name: http
---
{{/* Order Service */}}
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  selector:
    app: order-service
  ports:
    - port: {{ .Values.orderService.service.port }}
      targetPort: {{ .Values.orderService.service.targetPort }}
      protocol: TCP
      name: http
---
{{/* Product Service */}}
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  selector:
    app: product-service
  ports:
    - port: {{ .Values.productService.service.port }}
      targetPort: {{ .Values.productService.service.targetPort }}
      protocol: TCP
      name: http
---
{{/* RabbitMQ Service */}}
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
      protocol: TCP
    - name: http
      port: 15672
      targetPort: 15672
      protocol: TCP